FROM mcr.microsoft.com/playwright:v1.50.0-noble

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN npx playwright install

COPY src/platform/db ./src/platform/db

COPY src/config.ts ./src/config.ts
COPY src/modules/scanner/config.ts ./src/modules/scanner/config.ts
COPY src/modules/notification/config.ts ./src/modules/notification/config.ts
COPY src/modules/github/config.ts ./src/modules/github/config.ts

COPY tests/e2e ./tests/e2e
COPY drizzle.config.ts ./
COPY playwright.config.ts ./
