FROM mcr.microsoft.com/playwright:v1.50.0-noble

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN npx playwright install

COPY src/db ./src/db
COPY src/domain ./src/domain
COPY src/config.ts ./src/config.ts
COPY tests/e2e ./tests/e2e
COPY drizzle.config.ts ./
COPY playwright.config.ts ./
